version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Incentive.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=incentive_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - incentive-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=incentive_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - incentive-network

volumes:
  postgres-data:

networks:
  incentive-network:
    driver: bridge
